# -*- encoding: utf-8 -*-

# External imports
from enum import Enum

class Action_Types(Enum):
    ACCEPT_ENTERPRISE_JOIN_REQUEST = "acceptEnterpriseJoinRequest"
    ADD_ATTACHMENT_TO_CARD = "addAttachmentToCard"
    ADD_CHECKLIST_TO_CARD = "addChecklistToCard"
    ADD_MEMBER_TO_BOARD = "addMemberToBoard"
    ADD_MEMBER_TO_CARD = "addMemberToCard"
    ADD_MEMBER_TO_ORGANIZATION = "addMemberToOrganization"
    ADD_ORGANIZATION_TO_ENTERPRISE = "addOrganizationToEnterprise"
    ADD_TO_ENTERPRISE_PLUGIN_WHITELIST = "addToEnterprisePluginWhitelist"
    ADD_TO_ORGANIZATION_BOARD = "addToOrganizationBoard"
    COMMENT_CARD = "commentCard"
    CONVERT_TO_CARD_FROM_CHECK_ITEM = "convertToCardFromCheckItem"
    COPY_BOARD = "copyBoard"
    COPY_CARD = "copyCard"
    COPY_COMMENT_CARD = "copyCommentCard"
    CREATE_BOARD = "createBoard"
    CREATE_CARD = "createCard"
    CREATE_LIST = "createList"
    CREATE_ORGANIZATION = "createOrganization"
    DELETE_BOARD_INVITATION = "deleteBoardInvitation"
    DELETE_CARD = "deleteCard"
    DELETE_ORGANIZATION_INVITATION = "deleteOrganizationInvitation"
    DISABLE_ENTERPRISE_PLUGIN_WHITELIST = "disableEnterprisePluginWhitelist"
    DISABLE_PLUGIN = "disablePlugin"
    DISABLE_POWER_UP = "disablePowerUp"
    EMAIL_CARD = "emailCard"
    ENABLE_ENTERPRISE_PLUGIN_WHITELIST = "enableEnterprisePluginWhitelist"
    ENABLE_PLUGIN = "enablePlugin"
    ENABLE_POWER_UP = "enablePowerUp"
    MAKE_ADMIN_OF_BOARD = "makeAdminOfBoard"
    MAKE_NORMAL_MEMBER_OF_BOARD = "makeNormalMemberOfBoard"
    MAKE_NORMAL_MEMBER_OF_ORGANIZATION = "makeNormalMemberOfOrganization"
    MAKE_OBSERVER_OF_BOARD = "makeObserverOfBoard"
    MEMBER_JOINED_TRELLO = "memberJoinedTrello"
    MOVE_CARD_FROM_BOARD = "moveCardFromBoard"
    MOVE_CARD_TO_BOARD = "moveCardToBoard"
    MOVE_LIST_FROM_BOARD = "moveListFromBoard"
    MOVE_LIST_TO_BOARD = "moveListToBoard"
    REMOVE_CHECKLIST_FROM_CARD = "removeChecklistFromCard"
    REMOVE_FROM_ENTERPRISE_PLUGIN_WHITELIST = "removeFromEnterprisePluginWhitelist"
    REMOVE_FROM_ORGANIZATION_BOARD = "removeFromOrganizationBoard"
    REMOVE_MEMBER_FROM_CARD = "removeMemberFromCard"
    REMOVE_ORGANIZATION_FROM_ENTERPRISE = "removeOrganizationFromEnterprise"
    UNCONFIRMED_BOARD_INVITATION = "unconfirmedBoardInvitation"
    UNCONFIRMED_ORGANIZATION_INVITATION = "unconfirmedOrganizationInvitation"
    UPDATE_BOARD = "updateBoard"
    UPDATE_CARD = "updateCard"
    UPDATE_CHECK_ITEM_STATE_ON_CARD = "updateCheckItemStateOnCard"
    UPDATE_CHECKLIST = "updateChecklist"
    UPDATE_LIST = "updateList"
    UPDATE_MEMBER = "updateMember"
    UPDATE_ORGANIZATION = "updateOrganization"
